spring:
  application:
    name: client-service
  cloud:
    config:
      uri: http://config-service:8081
      username: root
      password: s3cr3t
  boot:
    admin:
      client:
        url: http://admin-service:8086
  config:
    import: configserver:http://config-service:8081
