server:
  port: 8081

spring:
#  application:          # no va en el ejemplo
#    name: config-service # no va en el ejemplo
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Tech-Company-SW52/microservices.git
          searchPaths: config-data
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}
          default-label: "develop"
  security:
    user:
      name: root
      password: s3cr3t