spring:
  application:
    name: carrier-service
  cloud:
    config:
      uri: http://localhost:8081
      username: root
      password: s3cr3t
  boot:
    admin:
      client:
        url: http://localhost:8086
  config:
    import: configserver:http://localhost:8081